version: '3'

services:
  puppet:
    build:
      context: .
      dockerfile: Dockerfile.puppet
    restart: always
    container_name: puppet
    ports:
      - 8140
    volumes:
      - ./puppet/ssl:/etc/puppetlabs/puppet/ssl/
      - ./puppet/serverdata:/opt/puppetlabs/server/data/puppetserver/

  redis:
    restart: always
    image: sameersbn/redis:latest
    command:
    - --loglevel warning
    volumes:
    - /srv/docker/gitlab/redis:/var/lib/redis:Z

  postgresql:
    restart: always
    image: sameersbn/postgresql:9.6-2
    volumes:
    - /srv/docker/gitlab/postgresql:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm

  gitlab:
    restart: always
    image: sameersbn/gitlab:9.0.5
    depends_on:
    - redis
    - postgresql
    ports:
    - "10080:80"
    - "10022:22"
    #volumes:
    #- /srv/docker/gitlab/gitlab:/home/git/data:Z
    env_file:
    - gitlab.env

  gitlab-cli:
    build:
      context: .
      dockerfile: Dockerfile.gitlab-cli
      args:
        GITLAB: gitlab
    container_name: gitlab-cli
    depends_on:
    - gitlab
    environment:
    - GITLAB_API_ENDPOINT=http://gitlab/api/v4 
    - GITLAB_API_PRIVATE_TOKEN=$TOKEN
    command: create_project test

  runner:
    restart: always
    image: gitlab/gitlab-runner
    depends_on:
    - gitlab
    volumes:
    - ./data/gitlab-runner:/etc/gitlab-runner
    - /var/run/docker.sock:/var/run/docker.sock
